name: Docker Image CI

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Release1'
    steps:
    - name: Step1Job1
      run: |
        sleep 10
        echo "Step1Job1"

  job2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Release3'
    steps:
    - name: Step1Job2
      run: |
        sleep 10
        echo "Step1Job2"
